name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*' # Also trigger on version tags like v1.0.0

env:
  REGISTRY: ghcr.io # Or docker.io, your-aws-account-id.dkr.ecr.your-region.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for pushing to GitHub Container Registry

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }} # Your GitHub username
        password: ${{ secrets.GITHUB_TOKEN }} # Or a PAT for other registries

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          type=semver,pattern=v{{version}} # For tags like v1.0.0
          type=sha,format=long,prefix=sha- # For commit SHAs
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }} # Latest for default branch

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha # Caching for faster builds
        cache-to: type=gha,mode=max # Caching for faster builds
